version: "2"

linters:
  enable:
    - gosec
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - gocritic
    - misspell
    - noctx
    - prealloc
    - reassign
    - sqlclosecheck
    - tparallel
    - unconvert
    - wastedassign
  settings:
    gosec:
      excludes:
        - G104
