# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
      #- CC=x86_64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - amd64
  - id: linux-arm
    env:
      - CGO_ENABLED=1
      #- CC=arm-linux-gnueabihf-gcc
    goos:
      - linux
    goarch:
      - arm
  - id: linux-arm64
    env:
      - CGO_ENABLED=1
      #- CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
  - id: others
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
